version: "3.9"

services:
    pg-db:
        image: postgres:14-alpine
        ports:
            - "5431:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
    boilerplate:
        image: go-boilerplate-v2
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - pg-db
        ports:
            - "8081:8081"
        env_file:
            - .env
